### ISSUE TITLE
test_database_error_quote is incorrectly implemented

### ISSUE THREAD

**Issue by shravanasati** [python-discord/code-jam-11-qualifier#4]
Hi, in the following test case, the assertion is wrong.

```py    
def test_database_error_quote(self):
        test_case = 'Nobody expects the Spanish Inquisition!'


        expected_output = "Quote has already been added previously\n"


        captured_output = io.StringIO()
        sys.stdout = captured_output


        qualifier.run_command(f'quote "{test_case}"')
        qualifier.run_command(f'quote "{test_case}"')


        output = captured_output.getvalue()
        self.assertEqual(output, expected_output)


        sys.stdout = sys.__stdout__
```

This is because the actual output after running two commands would be 
```
Nobody expects the Spanish Inquisition!
Quote has already been added previously
```
While the test case is comparing against the output of only the second `run_command` call.

We could either start capturing output after the first command or change the `expected_output` variable to include the test case string.

**Comment by vibhumeh** [comment]
Why did you print "Nobody expects the Spanish Inquisition!"?

**Comment by vibhumeh** [comment]
Removing that print statement will solve your issue. We need not print all the quotes added to the database.

**Comment by shravanasati** [comment]
You're right. Somehow I was under the impression I had to print every quote. Thank you.
